#!/bin/bash

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

# Install luks utilities if needed.
if [ "$(mount | grep "$CHROOT " | cut -c -16)" = "/dev/mapper/luks" ]; then
    echo "UMASK=0077" > "$CHROOT/etc/initramfs-tools/conf.d/initramfs-permissions"
    chroot "$CHROOT" apt-get -y install cryptsetup-initramfs cryptsetup keyutils
fi

echo "Running bootloader-config..."

if [ -d /sys/firmware/efi/efivars ]; then
    echo " * Installing grub-efi (uefi)..."
    DEBIAN_FRONTEND=noninteractive chroot "$CHROOT" apt-get -y install grub-efi
else
    echo " * Installing grub-pc (bios)..."
    DEBIAN_FRONTEND=noninteractive chroot "$CHROOT" apt-get -y install grub-pc
fi

# Re-enable os-prober for dual-boot.
sed -i "s/#GRUB_DISABLE_OS_PROBER=false/# OS_PROBER re-enabled by GamebianUbuntu Calamares installation:\nGRUB_DISABLE_OS_PROBER=false/g" \
    "$CHROOT/etc/default/grub"
chroot "$CHROOT" /usr/sbin/update-grub
