"""Write theme config to disk (GTK, Openbox, wallpaper path, session env)."""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path


CONFIG_DIR = Path.home() / ".config" / "gamebian"
THEME_JSON = CONFIG_DIR / "theme.json"
WALLPAPER_FILE = CONFIG_DIR / "wallpaper"
SESSION_ENV = CONFIG_DIR / "session-env.sh"
GTK3_SETTINGS = Path.home() / ".config" / "gtk-3.0" / "settings.ini"
GTK2_RC = Path.home() / ".gtkrc-2.0"
OB_RC = Path.home() / ".config" / "openbox" / "rc.xml"

THEME_IDS = ("gamebian", "gamebian-installed")


def ensure_config_dir() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)


def save_theme_json(wallpaper: str | None, gtk_theme: str, openbox_theme: str) -> None:
    ensure_config_dir()
    data = {
        "wallpaper": wallpaper or "",
        "gtk_theme": gtk_theme,
        "openbox_theme": openbox_theme,
    }
    THEME_JSON.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def write_wallpaper_path(path: str | None) -> None:
    ensure_config_dir()
    if path and Path(path).is_file():
        WALLPAPER_FILE.write_text(path.strip() + "\n", encoding="utf-8")
    else:
        if WALLPAPER_FILE.exists():
            WALLPAPER_FILE.unlink()


def write_session_env(gtk_theme: str) -> None:
    ensure_config_dir()
    if gtk_theme not in THEME_IDS:
        raise ValueError(f"Unknown GTK theme: {gtk_theme}")
    SESSION_ENV.write_text(
        f"# Generated by gamebian-theme — sourced from openbox autostart (top of file).\n"
        f'export GTK_THEME="{gtk_theme}"\n',
        encoding="utf-8",
    )


def write_gtk3_settings(gtk_theme: str, icon_theme: str = "Papirus") -> None:
    if gtk_theme not in THEME_IDS:
        raise ValueError(f"Unknown GTK theme: {gtk_theme}")
    GTK3_SETTINGS.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "[Settings]\n"
        f"gtk-theme-name={gtk_theme}\n"
        f"gtk-icon-theme-name={icon_theme}\n"
        "gtk-application-prefer-dark-theme=true\n"
        "gtk-font-name=Sans 10\n"
    )
    GTK3_SETTINGS.write_text(text, encoding="utf-8")


def write_gtk2_rc(gtk_theme: str, icon_theme: str = "Papirus") -> None:
    if gtk_theme not in THEME_IDS:
        raise ValueError(f"Unknown GTK theme: {gtk_theme}")
    GTK2_RC.write_text(
        f'gtk-theme-name = "{gtk_theme}"\n'
        f'gtk-icon-theme-name = "{icon_theme}"\n'
        'gtk-font-name="Sans 10"\n',
        encoding="utf-8",
    )


def patch_openbox_theme_name(rc_path: Path, openbox_theme: str) -> bool:
    """Set first <theme>…<name>…</name> to openbox_theme. Returns False if file missing."""
    if openbox_theme not in THEME_IDS:
        raise ValueError(f"Unknown Openbox theme: {openbox_theme}")
    if not rc_path.is_file():
        return False
    raw = rc_path.read_text(encoding="utf-8")
    new_raw, n = re.subn(
        r"(<theme>\s*<name>)([^<]+)(</name>)",
        rf"\g<1>{openbox_theme}\g<3>",
        raw,
        count=1,
        flags=re.MULTILINE,
    )
    if n != 1:
        return False
    rc_path.write_text(new_raw, encoding="utf-8")
    return True


def load_saved() -> dict:
    if not THEME_JSON.is_file():
        return {}
    try:
        return json.loads(THEME_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def apply_feh(wallpaper: str | None) -> tuple[bool, str]:
    if not wallpaper or not Path(wallpaper).is_file():
        return False, "No readable wallpaper file."
    feh = shutil.which("feh")
    if not feh:
        return False, "feh not found in PATH."
    import subprocess

    r = subprocess.run(
        [feh, "--no-fehbg", "--bg-fill", wallpaper],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        err = (r.stderr or r.stdout or "").strip()
        return False, err or f"feh exited {r.returncode}"
    return True, ""


def reconfigure_openbox() -> tuple[bool, str]:
    ob = shutil.which("openbox")
    if not ob:
        return False, "openbox not in PATH."
    import subprocess

    r = subprocess.run([ob, "--reconfigure"], capture_output=True, text=True)
    if r.returncode != 0:
        err = (r.stderr or r.stdout or "").strip()
        return False, err or f"openbox --reconfigure failed ({r.returncode})"
    return True, ""


def restart_lxpanel() -> None:
    ctl = shutil.which("lxpanelctl")
    if not ctl:
        return
    import subprocess

    subprocess.run([ctl, "restart"], capture_output=True, text=True)
