# Bootloader configuration for GRUB on the installed system.
---
efiBootLoader: "grub"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

installEFIFallback: true
