#!/bin/sh
# Prefer Desktop (Openbox) session on next boot.
set -eu

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin${PATH:+:$PATH}"

rm -f /etc/lightdm/lightdm.conf.d/90-gamebian-openbox-first-session.conf
rm -f /etc/lightdm/lightdm.conf.d/99-gamebian-steam-session.conf
rm -f /etc/lightdm/lightdm.conf.d/88-gamebian-openbox-session.conf
rm -f /etc/lightdm/lightdm.conf.d/97-gamebian-autologin-steam.conf
rm -f /etc/lightdm/lightdm.conf.d/99-gamebian-autologin-steam.conf

if [ -r /usr/share/gamebian/gamebian-lightdm-user.sh ]; then
	# shellcheck disable=SC1091
	. /usr/share/gamebian/gamebian-lightdm-user.sh
	_home="$(gamebian_lightdm_user_home)" || _home=""
	if [ -n "${_home}" ]; then
		_u="$(gamebian_lightdm_autologin_user)"
		mkdir -p "${_home}/.config/gamebian"
		: >"${_home}/.config/gamebian/prefer-openbox-desktop"
		[ -n "${_u}" ] && chown -R "${_u}:${_u}" "${_home}/.config/gamebian" 2>/dev/null || true
	fi
fi

exit 0
